<?php
$z[0]=Array("global","",70,96);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",142,172);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",211,238);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",246,286);
$z[3][4]['filename']="head_init.htm";
$z[4]=Array("include","",307,341);
$z[4][4]['filename']="nav.htm";
$z[5]=Array("field","",448,470);
$z[5][4]['name']="typename";
$z[6]=Array("include","",3192,3229);
$z[6][4]['filename']="footer.htm";

?>