<?php
$z[0]=Array("global","",70,96);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",142,172);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",211,238);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",246,286);
$z[3][4]['filename']="head_init.htm";
$z[4]=Array("include","",307,341);
$z[4][4]['filename']="nav.htm";
$z[5]=Array("type","[field:typename /]",447,499);
$z[5][4]['typeid']="2";
$z[6]=Array("field","",776,798);
$z[6][4]['name']="typename";
$z[7]=Array("field","",829,848);
$z[7][4]['name']="title";
$z[8]=Array("field","",910,970);
$z[8][4]['name']="pubdate";
$z[8][4]['function']="MyDate('Y年m月d日 ',@me)";
$z[9]=Array("adminname","",1011,1028);
$z[10]=Array("field","",1103,1121);
$z[10][4]['name']="body";
$z[11]=Array("prenext","",1183,1208);
$z[11][4]['get']="pre";
$z[12]=Array("prenext","",1229,1255);
$z[12][4]['get']="next";
$z[13]=Array("include","",1564,1601);
$z[13][4]['filename']="footer.htm";

?>