<?php
$z[0]=Array("global","",99,131);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",384,410);
$z[1][4]['name']="cfg_powerby";
$z[2]=Array("global","",470,495);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("global","",497,525);
$z[3][4]['name']="cfg_indexname";
$z[4]=Array("channel","\r\n        <a href=\"[field:typeurl/]\">[field:typename/]</a>\r\n        ",539,648);
$z[4][4]['type']="top";
$z[5]=Array("global","",1108,1140);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",1177,1209);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("global","",1248,1280);
$z[7][4]['name']="cfg_templets_siin";
$z[8]=Array("global","",1518,1550);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("global","",1878,1910);
$z[9][4]['name']="cfg_templets_skin";

?>