<?php
$z[0]=Array("global","",70,96);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",142,172);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",211,238);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",246,286);
$z[3][4]['filename']="head_init.htm";
$z[4]=Array("include","",307,341);
$z[4][4]['filename']="nav.htm";
$z[5]=Array("type","[field:typename /]",447,499);
$z[5][4]['typeid']="2";
$z[6]=Array("channel","\r\n      <li class=\"list\">[field:typename/]</li>\r\n      ",738,833);
$z[6][4]['type']="sun";
$z[7]=Array("arclist","\r\n          <li class=\"news_list\">\r\n             <time class=\"time\">[field:pubdate function=MyDate('y-m-d',@me)/]</time>\r\n             <h1 class=\"title\">[field:title/]</h1>\r\n             <a href=\"[field:arcurl/]\" class=\"more\">查看更多<span class=\"icon_right\"></span></a>\r\n             <span class=\"line_bottom\"></span>\r\n          </li>\r\n          ",1066,1466);
$z[7][4]['typeid']="5";
$z[7][4]['row']="10";
$z[8]=Array("pagelist","",1964,2029);
$z[8][4]['listitem']="info,pre,next";
$z[8][4]['listsize']="5";
$z[8][4]['typeid']="5";
$z[9]=Array("page","",2043,2069);
$z[9][4]['pagesize']="10";
$z[10]=Array("arclist","\r\n            <li class=\"news_list\">\r\n               <time class=\"time\">[field:pubdate function=MyDate('y-m-d',@me)/]</time>\r\n               <h1 class=\"title\">[field:title/]</h1>\r\n               <a href=\"[field:arcurl/]\" class=\"more\">查看更多<span class=\"icon_right\"></span></a>\r\n               <span class=\"line_bottom\"></span>\r\n            </li>\r\n            ",2141,2555);
$z[10][4]['typeid']="6";
$z[10][4]['row']="10";
$z[11]=Array("pagelist","",2569,2634);
$z[11][4]['listitem']="info,pre,next";
$z[11][4]['listsize']="5";
$z[11][4]['typeid']="6";
$z[12]=Array("page","",2648,2685);
$z[12][4]['pagesize']="10";
$z[12][4]['typeid']="6";
$z[13]=Array("include","",3055,3092);
$z[13][4]['filename']="footer.htm";

?>