<?php
$z[0]=Array("global","",70,96);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",142,172);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",211,238);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",246,286);
$z[3][4]['filename']="head_init.htm";
$z[4]=Array("include","",307,341);
$z[4][4]['filename']="nav.htm";
$z[5]=Array("channel","\r\n      <li class=\"list\">[field:typename/]</li>\r\n      ",698,793);
$z[5][4]['type']="sun";
$z[6]=Array("arclist","\r\n          <li class=\"news_list\">\r\n             <time class=\"time\">[field:pubdate function=MyDate('y-m-d',@me)/]</time>\r\n             <h1 class=\"title\">[field:title/]</h1>\r\n             <a href=\"[field:arcurl/]\" class=\"more\">查看更多<span class=\"icon_right\"></span></a>\r\n             <span class=\"line_bottom\"></span>\r\n          </li>\r\n          ",1026,1426);
$z[6][4]['row']="10";
$z[6][4]['typeid']="5";
$z[7]=Array("arclist","\r\n            <li class=\"news_list\">\r\n               <time class=\"time\">[field:pubdate function=MyDate('y-m-d',@me)/]</time>\r\n               <h1 class=\"title\">[field:title/]</h1>\r\n               <a href=\"[field:arcurl/]\" class=\"more\">查看更多<span class=\"icon_right\"></span></a>\r\n               <span class=\"line_bottom\"></span>\r\n            </li>\r\n            ",1684,2098);
$z[7][4]['row']="10";
$z[7][4]['typeid']="6";
$z[8]=Array("include","",2361,2398);
$z[8][4]['filename']="footer.htm";

?>