<?php
$z[0]=Array("global","",155,187);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",326,351);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("global","",400,428);
$z[2][4]['name']="cfg_indexname";
$z[3]=Array("type","\r\n        <li><a href=\"/ch/product.html\"><span class=\"icon_shop\" title=\"[field:typename/]\"></span>[field:typename/]</a></li>\r\n        ",447,615);
$z[3][4]['typeid']="1";
$z[4]=Array("type","\r\n        <li><a href=\"[field:typeurl/]\"><span class=\"icon_news\" title=\"[field:typename/]\"></span>[field:typename/]</a></li>\r\n        ",625,793);
$z[4][4]['typeid']="2";
$z[5]=Array("type","\r\n        <li><a href=\"[field:typeurl/]\"><span class=\"icon_contacts\" title=\"[field:typename/]\"></span>[field:typename/]</a></li>\r\n        ",803,975);
$z[5][4]['typeid']="3";
$z[6]=Array("type","\r\n        <li><a href=\"[field:typeurl/]\"><span class=\"icon_about\" title=\"[field:typename/]\"></span>[field:typename/]</a></li>\r\n        ",985,1154);
$z[6][4]['typeid']="4";
$z[7]=Array("channel","\r\n            <li><a href=\"[field:typeurl/]\"><span class=\"icon_news\" title=\"[field:typename/]\"></span>[field:typename/]</a></li>\r\n        ",1173,1370);
$z[7][4]['type']="top";
$z[7][4]['typeid']="2";
$z[7][4]['row']="1";
$z[8]=Array("channel","\r\n            <li><a href=\"[field:typeurl/]\"><span class=\"icon_contacts\" title=\"[field:typename/]\"></span>[field:typename/]</a></li>\r\n        ",1380,1581);
$z[8][4]['type']="top";
$z[8][4]['typeid']="3";
$z[8][4]['row']="1";
$z[9]=Array("channel","\r\n            <li><a href=\"[field:typeurl/]\"><span class=\"icon_about\" title=\"[field:typename/]\"></span>[field:typename/]</a></li>\r\n        ",1591,1789);
$z[9][4]['type']="top";
$z[9][4]['typeid']="4";
$z[9][4]['row']="1";

?>