<?php
$z[0]=Array("global","",236,264);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",277,296);
$z[1][4]['name']="title";
$z[2]=Array("global","",297,323);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",364,386);
$z[3][4]['name']="keywords";
$z[4]=Array("field","",426,477);
$z[4][4]['name']="description";
$z[4][4]['function']="html2text(@me)";
$z[5]=Array("global","",495,527);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("include","",845,880);
$z[6][4]['filename']="head.htm";
$z[7]=Array("field","",1046,1072);
$z[7][4]['name']="title";
$z[8]=Array("field","",1157,1176);
$z[8][4]['name']="title";
$z[9]=Array("field","",1244,1262);
$z[9][4]['name']="body";
$z[10]=Array("likesgpage","\r\n      <li><a href=\"[field:url /]\">[field:title /]</a></li>\r\n  ",1468,1567);
$z[11]=Array("include","",1647,1684);
$z[11][4]['filename']="footer.htm";

?>